sudo: required
os: linux
dist: bionic
language: python
python:
  - "3.7"
git:
  quiet: true
  submodules: false
branches:
  only:
    - master

install:
  - pip install yamllint
  - sudo snap install yq

script:
  - yamllint images
  - |
    if [ ${TRAVIS_PULL_REQUEST} != "false" ]; then
      bash ${TRAVIS_BUILD_DIR}/scripts/deploy/quarantine.sh
    fi

before_deploy:
  # Prepare codedeploy artifact
  - bash ${TRAVIS_BUILD_DIR}/scripts/deploy/deploy.sh
  # Package codedeploy artifact
  - zip -qr latest appspec.yml scripts
  - test -d "${deploy_dir}" || mkdir "${deploy_dir}"
  - mv latest.zip "${deploy_dir}/${deploy_artifact}"

deploy:
  - provider: s3
    region: ${AWS_DEFAULT_REGION}
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: ${S3_TARGET_BUCKET}
    skip_cleanup: true
    local_dir: codedeploy
    on:
      branch: master
  - provider: codedeploy
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: ${S3_TARGET_BUCKET}
    key: artifact-${TRAVIS_COMMIT}.zip
    application: ${CODEDEPLOY_APPLICATION_NAME}
    deployment_group: master
    region: ${AWS_DEFAULT_REGION}
    wait_until_deployed: true
    on:
      branch: master
